### ISSUE TITLE
Where to submit feedback / suggestions / issues for PCF tile?

### ISSUE THREAD

**Issue by aegershman** [minio/minio-pcf-adapter#1]
Hey there,

As an operator whose trying out minio for PCF for the first time, I have some feedback / suggestions on how the minio PCF tile could be improved (for example, recommendations for better default configuration values).

- Is there a repository where those issues should be placed, e.g. the repo which holds the source code for packaging the [actual minio tile available on pivnet?](https://network.pivotal.io/products/minio/) 
- And presumably any feedback about the pcf minio on-demand service broker itself should go here? (e.g., suggestions on what things should be configurable for service plan definitions and such)

Thank you!

**Comment by krishnasrinivas** [comment]
@aegershman Feedback will be very helpful. Can you please provide the feedback here? The tile itself has not been open sourced as it is not useful outside the PCF environment.
