### ISSUE TITLE
Migrate to xenial stemcells

### ISSUE THREAD

**Issue by aegershman** [minio/minio-pcf-adapter#5]
Because the `trusty` line of stemcells will be deprecated in sometime of April 2019, the minio service broker should migrate from using `trusty` stemcells to the `xenial` line of stemcells.

E.g., the minio 1.0.0 service broker is using the `3468.*` line of stemcells, but will eventually need to move to the `97.*` (xenial) line of stemcells.

![screen shot 2018-11-05 at 12 36 22 pm](https://user-images.githubusercontent.com/5619476/48018806-70464f00-e0f7-11e8-9e7a-22a50575842f.png)

**Comment by krishnasrinivas** [comment]
Got it, we'll be fixing this in the next version of the tile.

**Comment by krishnasrinivas** [comment]
Fixed in the tile release 1.0.1
